// src/components/books/BookBlockDisplay.svelte
<template>
<!--{blockRid}->{blockListObj.blockId}->{blockListObj.loaded}->{blockListObj.visible}-->
{#if block && block.getClass}
  <div data-rid="{blockRid}" id="{block.blockid}" data-id="{block.blockid}" class="ilm-block ilm-display -langblock-{block.language} {blockOutPaddings()}">
  {#if block.type === 'illustration'}
    <img alt="block.blockid" class="{block.getClass()}" src="{getIllustration()}"/>
  {:else if block.type === 'hr'}
    <hr class="{block.getClass()}"/>
  {:else}
    {#if getParnum()}
      <div class="bview-parnum">{getParnum()}</div>
    {/if}

    <div id="display-{block.blockid}" lang="{block.language}"
      class="bview-content part-0 {block.getClass ? block.getClass() : ''} hide-archive"
      data-parnum="{getParnum()}"
      data-type="{block.type}"
      on:click={handleFootnote}>
      {#if blockListObj.loaded}{@html block.content}{/if}
    </div>

    {#if block.footnotes.length > 0}
    <div class="footnotes">
      {#each block.footnotes as footnote, footnoteIdx}
      <div class="-hidden" bind:this={footNotes[footnote.ftnIdx]}>
        <div class="-langftn-{footnote.language}">
          <div class="-num">[fn{footnote.ftnIdx+1}]</div>
          <div  class="-text">
            {@html footnote.content}
          </div>
        </div>
      </div>
      {/each}
    </div>
    {/if}

  {/if}
  </div>
{:else}
  <div class="ilm-block ilm-display content-process-run preloader-loading"></div>
{/if}
<div class="clearfix"></div>
</template>
<script>

  //import { fade } from 'svelte/transition';

  export let block;
  export let blockListObj;
  export let idx;
  export let blockRid = '';
  export let isLoaded = false;

  let footNotes = {};

  let getRandomInt = (min, max)=>{
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min)) + min; //The maximum is exclusive and the minimum is inclusive
  }
  //let rand = getRandomInt(0, 200);

  const getIllustration = () => {
    return (block && block.getIllustration) ? block.getIllustration() : '';
  }

  const blockOutPaddings = () => {
    if (block) {
      console.log('blockOutPaddings');
      return (block.classes && block.classes.hasOwnProperty('outsize-padding')) ? block.classes['outsize-padding'] : ''
    } else return '';
  }

  const getParnum = () => {
    if (block) {
      if (block.type == 'header' && block.isNumber && !block.isHidden) {
        return block.secnum;
      }
      else if (block.type == 'par' && block.isNumber && !block.isHidden) {
        return block.parnum;
      }
    }
    return false;
  }

  const handleFootnote = (ev) => {
    if (ev.target.dataset.idx && footNotes[ev.target.dataset.idx]) {
      let className = footNotes[ev.target.dataset.idx].className;
      if (className == '-hidden') {
        footNotes[ev.target.dataset.idx].className = '';
      } else footNotes[ev.target.dataset.idx].className = '-hidden';
    }
  }

</script>

<style>
  .ilm-block.ilm-display {
    position: relative;
  }
  .bview-parnum {
    padding-top: 10px;
    font-family: GentiumPlus, 'Georgia', 'serif';
    padding-left: 15px;
    color: rgba(26, 26, 26, 0.7);
    font-size: 12px;
    cursor: pointer;
    position: absolute;
    left: 0px;
    /*font-family: 'Georgia', 'serif';
    font-size: 10px;*/
  }
</style>

// src/components/books/BookBlockDisplay.vue
<template>
<section>
  <div v-if="loaded === true || blockO.loaded === true" ref="viewBlock" :data-id="blockId" :data-rid="blockRid" :id="blockId" :class="['ilm-block', 'ilm-display', '-langblock-' + blockView.language, blockOutPaddings]">

      <div v-if="blockO.type == 'illustration'" :class="getClass">
        <img :class="getClass" :src="getIllustration"/>
        <div class="getDescription"
        :class="['content-description', getClass]"
        v-if="getDescription.length"
        v-html="getDescription">
        </div>
      </div>
      <div v-else-if="blockO.type == 'hr'">
        <hr :class="[getClass]"/>
      </div>
      <div v-else >
        <div
          v-if="parnum && parnum.length"
          v-html="parnum"
          :class="['parnum']">
        </div>
        <div
          @click="handleFootnote($event)"
          :class="[getClass, 'hide-archive']"
          :id="blockId"
          :data-parnum="parnum"
          :lang="blockView.language"
          :data-type="blockO.type"
          v-html="blockView.content">
        </div>
        <div class="footnotes"
          v-if="blockView.footnotes.length > 0">
          <div class="-hidden" ref="footNotes"
            v-for="(footnote, footnoteIdx) in blockView.footnotes" >
            <div :class="['-langftn-' + footnote.language]">
              <div class="-num">[fn{{footnote.ftnIdx+1}}]</div>
              <div  class="-text" v-html="footnote.content">
              </div>
            </div>
          </div>
        </div>
      </div>

  </div>
  <div v-else ref="viewBlock" :data-id="blockId" :data-rid="blockRid" :id="blockId" :class="['ilm-block', 'ilm-display', 'content-process-run', 'preloader-loading']">
    <!--{{blockId}}/{{blockRid}}/{{blockO.loaded}}-->
  </div>

  <div class="clearfix"></div>
</section>
</template>

<script>
import Vue from 'vue'
import { BookBlock }    from '../../store/bookBlock'
import { mapGetters, mapState, mapActions } from 'vuex'

  export default {
    name: 'book-block-display',
    props: [
      'blockRid', 'blockO', 'lang', 'loaded'
    ],// loaded property is necessary for updating first part of loaded blocks, VueJS is not updating automatically
    data() {
      return {
        fntCounter: 0
      }
    },
    computed: {
      ...mapGetters({
        parlist: 'storeList'
      }),
      blockId: function() {
        return this.blockO.blockid;
      },
      block: function() {
        return this.parlist.get(this.blockId)
      },
      blockOutPaddings: function () {
        if (this.block) {
          return (this.block.classes && this.block.classes.hasOwnProperty('outsize-padding')) ? this.block.classes['outsize-padding'] : ''
        } else return '';
      },
      parnum: { cache: false,
        get: function () {
          if (this.blockO.type == 'header' && this.blockO.isNumber && !this.blockO.isHidden) {
            return this.blockO.secnum;
          }
          else if (this.blockO.type == 'par' && this.blockO.isNumber && !this.blockO.isHidden) {
            return this.blockO.parnum;
          }
          else return false;
        }
      },
      getClass: { cache: true,
        get: function () {
          return this.block.getClass();
        }
      },
      getIllustration: { cache: true,
        get: function () {
          return this.block.getIllustration();
        }
      },
      getDescription: { cache: true,
        get: function () {
          return this.block.description;
        }
      },
      blockView: function () {
        if (this.block) {
          let viewObj = { footnotes: this.block.footnotes, language: this.block.language || this.lang };//new BookBlock(this.block);//Object.assign({}, this.parlist.get(blockId));
          viewObj.content = this.block.content.replace(
            /[\s]*?<sup[\s]*?data-pg[\s]*?=[\s]*?['"]+(.*?)['"]+.*?>.*?<\/sup>/mig,
            '<span data-pg="$1"></span>'
          );
          //<sup class="service-info" data-pg="xxiii"><w class="service-info" data-sugg="">pg </w><w class="service-info" data-sugg="">xxiii</w></sup>
          viewObj.content = viewObj.content.replace(
            /[\s]*?<sup(?=\s)\s*?class=['"]{1}service-info['"]{1}\s*?data-pg=['"]{1}(.*?)['"]{1}[^>]*>.*?<\/sup>/mig,
            '<span class="service-info" data-pg="$1"></span>'
          );

          let ftnIdx = 0;
          viewObj.content = viewObj.content.replace(
            /[\s]*?<sup[\s]*?data-idx[\s]*?=[\s]*?['"]+(.*?)['"]+[^>]*>.*?<\/sup>/mig,
            (idx)=>{
              if (typeof viewObj.footnotes[ftnIdx] !== 'undefined') {
                viewObj.footnotes[ftnIdx].ftnIdx = this.fntCounter;
              }
              ftnIdx++;
              return `<sup data-idx="${this.fntCounter++}">[${this.fntCounter}]</sup>`
            }
          );
          //<sup class="service-info" data-idx="2"><w class="service-info" data-sugg="">2</w></sup>
          viewObj.content = viewObj.content.replace(
            /[\s]*?<sup(?=\s)\s*?class=['"]{1}service-info['"]{1}\s*?data-idx[\s]*?=[\s]*?['"]+(.*?)['"]+[^>]*>.*?<\/sup>/mig,
            (idx)=>{
              if (typeof viewObj.footnotes[ftnIdx] !== 'undefined') {
                viewObj.footnotes[ftnIdx].ftnIdx = this.fntCounter;
              }
              ftnIdx++;
              return `<sup class="service-info" data-idx="${this.fntCounter++}">[${this.fntCounter}]</sup>`
            }
          );
          return viewObj;
        } else return { footnotes: [], language: this.block.language || this.lang };
      }
    },
    methods: {
      handleFootnote: function (ev) {
        if (ev.target.dataset.idx && this.$refs.footNotes[ev.target.dataset.idx]) {
          let className = this.$refs.footNotes[ev.target.dataset.idx].className;
          if (className == '-hidden') {
            this.$refs.footNotes[ev.target.dataset.idx].className = '';
          } else this.$refs.footNotes[ev.target.dataset.idx].className = '-hidden';
        }
      }
    }
  }
</script>

<style lang='less' scoped>
  
</style>
